<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE restaurant_reviews [
        <!ELEMENT restaurant_reviews (restaurant)*>
        <!ELEMENT restaurant (image|name|logo|address|phone|reviews|menu)*>
        <!ELEMENT image (path|width|height)*>
        <!ELEMENT path (#PCDATA)>
        <!ELEMENT width (#PCDATA)>
        <!ATTLIST width
                unit CDATA #REQUIRED>
        <!ELEMENT height (#PCDATA)>
        <!ATTLIST height
                unit CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT logo (#PCDATA)>
        <!ELEMENT address (building_number|street|city|province|postal|country)*>
        <!ELEMENT building_number (#PCDATA)>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT province (#PCDATA)>
        <!ELEMENT postal (#PCDATA)>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT phone (area_code|number)*>
        <!ELEMENT area_code (#PCDATA)>
        <!ELEMENT number (#PCDATA)>
        <!ELEMENT reviews (review)*>
        <!ELEMENT review (reviewer_name|date|rating|summary)*>
        <!ELEMENT reviewer_name (first_name|middle_name|last_name)*>
        <!ELEMENT first_name (#PCDATA)>
        <!ELEMENT middle_name (#PCDATA)>
        <!ELEMENT last_name (#PCDATA)>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT rating (#PCDATA)>
        <!ELEMENT summary (#PCDATA)>
        <!ELEMENT menu (appetizers|entrees)*>
        <!ELEMENT appetizers (item)*>
        <!ELEMENT item (description|bulk_order|single_order|price|quantity)*>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT bulk_order (price|quantity)*>
        <!ELEMENT price (#PCDATA)>
        <!ATTLIST price
                currency CDATA #REQUIRED>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT single_order (price|quantity)*>
        <!ELEMENT entrees (item)*>
        ]>
<restaurant_reviews>

    <restaurant>

        <image>
            <path>laughing-man.gif</path>
            <width unit="pixels">50</width>
            <height unit="pixels">200</height>
        </image>

        <name>Laughing Man</name>
        <logo>Visit the Laughing Man</logo>

        <address>
            <building_number>2100</building_number>
            <street>Lakeview Road</street>
            <city>Kanata</city>
            <province>Ontario</province>
            <postal>K2K 2K7</postal>
            <country>Canada</country>
        </address>

        <phone>
            <area_code>613</area_code>
            <number>123-4567</number>
        </phone>

        <reviews>
            <review>
                <reviewer_name>
                    <first_name>Hunter</first_name>
                    <middle_name>S.</middle_name>
                    <last_name>Thompson</last_name>
                </reviewer_name>

                <date>2015-01-10</date>
                <rating>4</rating>
                <summary>Laughing Man Inn is a completely restored Victorian hotel, and offers a warm and elegant atmosphere and gracious service.</summary>
            </review>
        </reviews>

        <menu>
            <appetizers>
                <item>
                    <description>Crab cakes with a creamy dill sauce served with crispy herbed fries.</description>
                    <bulk_order>
                        <price currency="CAD"></price>
                        <quantity></quantity>
                    </bulk_order>
                    <single_order>
                        <price currency="CAD">23.00</price>
                        <quantity>1</quantity>
                    </single_order>
                </item>

                <item>
                    <description>Garden vegetable soup with chocolate sauce</description>
                    <bulk_order>
                        <price currency="CAD"></price>
                        <quantity></quantity>
                    </bulk_order>
                    <single_order>
                        <price currency="CAD">15.00</price>
                        <quantity>1</quantity>
                    </single_order>
                </item>
            </appetizers>
            <entrees>
                <item>
                    <description>Braised jumbo sea scallops on a sun-dried roast tomato base.</description>
                    <price currency="CAD">39.00</price>
                    <quantity>1</quantity>
                </item>
                <item>
                    <description>Free-range chicken breast stuffed with morels in a brandy sauce.</description>
                    <price currency="CAD">31.00</price>
                    <quantity>1</quantity>
                </item>
                <item>
                    <description>Roast pork loin on a bed of garlic ginger apple slaw.</description>
                    <price currency="CAD">34.00</price>
                    <quantity>1</quantity>
                </item>
            </entrees>
        </menu>
    </restaurant>

    <restaurant>

        <image>
            <path>gong-asian-cuisine.gif</path>
            <width unit="pixels">150</width>
            <height unit="pixels">250</height>
        </image>

        <name>Gong&apos;s Asian Cuisine</name>
        <logo></logo>

        <address>
            <building_number>1385</building_number>
            <street>Woodroffe Avenue</street>
            <city>Ottawa</city>
            <province>Ontario</province>
            <postal>K2G 1V8</postal>
            <country>Canada</country>
        </address>

        <phone>
            <area_code>613</area_code>
            <number>727-4723</number>
        </phone>

        <reviews>
            <review>
                <reviewer_name>
                    <first_name>Brenda</first_name>
                    <middle_name>P.</middle_name>
                    <last_name>Smith</last_name>
                </reviewer_name>

                <date>2015-01-3</date>
                <rating>3</rating>
                <summary>The food is always consistent. A good variety of dim sum, sushi, Chinese and even Vietnamese dishes. The service is quick and the food is plentiful. We sat down last night and within seconds of turning in our first order, the plates were on the table! The teriyaki dishes had the right amount of sauce and weren&apos;t sickeningly sweet. The chicken, fish, and beef were perfectly cooked. The maki-rolls were neatly rolled, cut properly and seasoned well. Loved the General Tao chicken, the steamed BBQ pork buns, the eel sushi and the lovely eggplant. We will be going back again! I would highly recommend it.</summary>
            </review>
        </reviews>

        <menu>
            <appetizers>
                <item>
                    <description>Egg Roll</description>
                    <bulk_order>
                        <price currency="CAD">15.00</price>
                        <quantity>12</quantity>
                    </bulk_order>
                    <single_order>
                        <price currency="CAD">1.50</price>
                        <quantity>1</quantity>
                    </single_order>
                </item>

                <item>
                    <description>Spring Roll</description>
                    <bulk_order>
                        <price currency="CAD">15.00</price>
                        <quantity>12</quantity>
                    </bulk_order>
                    <single_order>
                        <price currency="CAD">1.50</price>
                        <quantity>1</quantity>
                    </single_order>
                </item>

                <item>
                    <description>Shrimp Chips</description>
                    <bulk_order>
                        <price currency="CAD"></price>
                        <quantity></quantity>
                    </bulk_order>
                    <single_order>
                        <price currency="CAD">2.50</price>
                        <quantity>1</quantity>
                    </single_order>
                </item>

                <item>
                    <description>Fried Noodles</description>
                    <bulk_order>
                        <price currency="CAD"></price>
                        <quantity></quantity>
                    </bulk_order>
                    <single_order>
                        <price currency="CAD">1.00</price>
                        <quantity>1</quantity>
                    </single_order>
                </item>

                <item>
                    <description>Sweet &amp; Sour Fried Wonton Skin</description>
                    <bulk_order>
                        <price currency="CAD">3.50</price>
                        <quantity>12</quantity>
                    </bulk_order>
                    <single_order>
                        <price currency="CAD"></price>
                        <quantity></quantity>
                    </single_order>
                </item>
            </appetizers>
            <entrees>
                <item>
                    <description>Scallops with Vegetables</description>
                    <price currency="CAD">14.95</price>
                    <quantity>1</quantity>
                </item>
                <item>
                    <description>Sweet and Sour Fish Cantonese Style</description>
                    <price currency="CAD">13.95</price>
                    <quantity>1</quantity>
                </item>
                <item>
                    <description>Shrimps with Vegetables</description>
                    <price currency="CAD">12.95</price>
                    <quantity>1</quantity>
                </item>
                <item>
                    <description>Beef with Mushroom</description>
                    <price currency="CAD">10.25</price>
                    <quantity>1</quantity>
                </item>
                <item>
                    <description>Beef with Tomato</description>
                    <price currency="CAD">10.25</price>
                    <quantity>1</quantity>
                </item>
                <item>
                    <description>Beef with Broccoli</description>
                    <price currency="CAD">10.25</price>
                    <quantity>1</quantity>
                </item>
            </entrees>
        </menu>
    </restaurant>

</restaurant_reviews>